### ISSUE TITLE
(1.12) Poof! crashes.

### ISSUE THREAD

**Issue by Migmag789** [lumien231/Random-Things#227] opened 2017-07-17 09:16 UTC
I'm launching my modpack, and... Poof! crashes.
[crash-2017-07-17_11.03.47-client.txt](https://github.com/lumien231/Random-Things/files/1152066/crash-2017-07-17_11.03.47-client.txt)
I have adverted all the other mods authors because Quark, Morpheus, Blur and CyclopsCore have crashed too.

**Comment by lumien231** [comment] 2017-07-17 22:27
This crash is caused by Malisis Doors, will be fixed there :).

**Closed as completed by lumien231** 2017-07-17 22:27 UTC
