### ISSUE TITLE
[1.12.2] Crash with latest JEI version

### ISSUE THREAD

**Issue by TheLimePixel** [lumien231/Random-Things#245] opened 2017-09-25 20:06 UTC
When looking for something from Random Things in JEI, the client crashes:
https://pastebin.com/29yChzjj

**Comment by Zedrimar** [comment] 2017-09-26 03:02
I can confirm this and can narrow it down to the luminous blocks

**Comment by Zedrimar** [comment] 2017-09-26 03:17
funny enough, NEI doesn't make it crash but JEI viewing mode WILL crash it

**Comment by lumien231** [comment] 2017-09-26 07:45
Duplicate of #242

**Closed as completed by lumien231** 2017-09-26 07:45 UTC
