### ISSUE TITLE
Diaphanous Blocks cause client crash

### ISSUE THREAD

**Issue by DennHenda** [lumien231/Random-Things#324] opened 2018-07-21 18:34 UTC
Immediately after placing a Diaphanous block, my client crashed. On my small private server now every time I log in it crashes, the server does not crash.
Also happens on single player.

https://paste.dimdev.org/izujeqerih.mccrash

**Comment by lumien231** [comment] 2018-07-22 14:14
Duplicate of #316

Fix will be in 4.2.0

**Closed as completed by lumien231** 2018-07-22 14:14 UTC
