### ISSUE TITLE
Crash w/ Extra Utils 2

### ISSUE THREAD

**Issue by WenXin20** [lumien231/Random-Things#142] opened 2016-10-05 19:20 UTC
Forge 1.10.2-2092
Random Things 3.7.6
[Extra Utils 1.1.0a](https://minecraft.curseforge.com/projects/extra-utilities)
Crash on load w/ the newest Extra Utils version
[Crash Log](http://pastebin.com/vmg81MtJ)

**Comment by lumien231** [comment] 2016-10-05 22:11
How do you know it's Extra Utilities & Random Things? Can you reproduce this with only those 2 mod installed?

**Comment by UnNinja** [comment] 2016-10-05 22:43
I was actually just about to open a report for this. Random Things works fine with earlier versions of ExtraUtilities, but things go splat when I try and update extra utilities

**Comment by WenXin20** [comment] 2016-10-06 02:23
Yeah, that's what happened to me, after I downgraded extra Utils back to 1.0.1, random things worked fine.

**Comment by WenXin20** [comment] 2016-10-06 04:08
I just tried just these two mods by themselves and it worked fine, it looks like the could be a third mod involved.

**Comment by UnNinja** [comment] 2016-10-06 21:46
Looks like this is ExU and Optifine, more than exu and randomthings

**Comment by lumien231** [comment] 2016-10-06 21:47
I think it might be load order dependent so whether it crashes with a certain set of mods is kinda random. It would be interesting if you could reproduce it only with or without optifine installed.

**Comment by lumien231** [comment] 2016-10-07 12:19
Ok so it does actually appear to happen with Optifine & Extra Utilities installed.

**Comment by sp614x** [comment] 2016-10-12 12:49
Found the problem, it only happens with mods which use delayed sprite registration.
Updated preview OptiFine C4 with a bugfix.

**Comment by lumien231** [comment] 2016-10-12 14:38
Neat :), just tried it and it seems to work fine now. Closing this.

**Closed as completed by lumien231** 2016-10-12 14:38 UTC

**Comment by xChitose** [comment] 2016-10-13 09:04
How did you come upon the solution, @sp614x ?

**Comment by sp614x** [comment] 2016-10-13 10:20
One Forge hook was missing from TextureMap. 
It can be used by mods to organize delayed atlas sprite registration, which is rarely used.
